### PR TITLE
s/http/https

### PR DESCRIPTION
**Pull request by MarcoPolo**

### CODE REVIEW

**Comment by altendo** [comment]
I think it should be stated that it can be accessed over http or https, to give people the option, since that was the intent according to @kinghrothgar

**Comment by altendo** [comment]
but I'm fine leaving the examples as https

**Comment by MarcoPolo** [comment]
no

**Comment by MarcoPolo** [comment]
There's no real benefit in doing http. If you really really want that I think it's okay to make you work a lil' extra for it

**Comment by MarcoPolo** [comment]
but the lazy copy/paste mode should give you the safe behavior and not let you 🔫 your 👣

**Comment by altendo** [comment]
no argument there, the examples should be https. I'm just saying that the info page should reflect that both work (because both work)

**Pull request merged**
